### ISSUE TITLE
Ecto 2.1 Compatibility

### ISSUE THREAD

**Issue by ankhers** [ankhers/mongodb_ecto#109]
#91 has now been merged into #84 and there in an impending release. I figure there should be an update for Ecto 2.1.

The work is currently being done in #123 

**NOTE:** The `ecto-2.1` branch is far from complete. If you need a working version of this adapter, please use the `ecto-2` branch.

**Comment by mbenatti** [comment]
@ankhers I'm working with this branch(`https://github.com/mbenatti/mongodb_ecto/tree/ecto-2.1/`) using ecto 2.1, until now everything are working fine

**Comment by ankhers** [comment]
Would you be able to package that up into a PR so that we may be able to get it merged into this repository?

**Comment by mbenatti** [comment]
@ankhers here: https://github.com/michalmuskala/mongodb_ecto/pull/122, its good to create a new branch for 2.1

**Comment by mbenatti** [comment]
For work with mongodb 0.3.0
- [ ] remove %BSON.DateTime{} (as it was removed from mongodb)

**Comment by hveiras** [comment]
Hi @mbenatti, @ankhers . I was looking some way to contribute to this project. Is there anything I can help you with 2.1 support?

**Comment by ankhers** [comment]
@mbenatti SSL support is already there, the options just get passed down to the `mongodb` driver. If anything, maybe just some documentation may be needed here. I would have to double check though. Please feel free to support using SSL through a URL though.

@hveiras Just fork the repository and run the tests. If you fix anything, please create a Pull Request to have it merged into the `ecto-2.1` branch. I would suggest fixing the loaders and dumpers for removing `BSON.DateTime` in favour of `DateTime`, but it looks like @mbenatti may be working on that.

**Comment by mikepc** [comment]
With a new phoenix project, I can't integrate mongodb_ecto yet. I've pointed it at the 2.1 branch but I'm seeing lib/mongo_ecto.ex:440: BSON.DateTime.__struct__/0 is undefined, cannot expand struct BSON.DateTime

I'm new to elixir/phoenix, what can I do to connect ecto_mongodb to my existing mongodb? I don't want to use the native mongodb driver. Are there any repos that can succesfully connect? What versions (specifically) can I configure my dependencies to so that it will work?

**Comment by ankhers** [comment]
There has not been much work done on the `ecto-2.1` branch. Unless you are attempting to make it work, I would advise against using it. You should be using the `ecto-2` branch if you want to use a stable version of this adapter.

Another thing, you are pointing to a fork of this repository where we have no control over what they put into the code.

**Comment by ankhers** [comment]
Just to note, the `ecto-2.1` branch should be "working" at the moment. I have gone through and made various fixes for things. The on conflict stuff introduced by Ecto 2.1 does not work at all right now though. But things should compile and be relatively useable. 

If you do start using it, please make a note either here or on #123 if you run into any issues and I will see what I can do about fixing it.

**Comment by ankhers** [comment]
I have just released v0.2.0 of this adapter. I will be closing this issue and opening a new one with known compatibility issues that need to be fixed.
