### ISSUE TITLE
It's possível to execute a query modify?

### ISSUE THREAD

**Issue by allanbatista** [ankhers/mongodb_ecto#126]
Hi, i'm try to use a query modify. But without success.

The query that i want to use is like that:

`
    db.getCollection('cities').find(
        { $text: { $search: "rj" } },
       { score: { $meta: "textScore" }
    }).sort( { score: { $meta: "textScore" } } )
`

Any idea how?

**Comment by scottmessinger** [comment]
@allanbatista Could you paste in the code you're trying to use? You'll likely want to try using a `fragment` in your `where` query.

**Comment by ankhers** [comment]
Closing due to lack of response.
