### ISSUE TITLE
Mongo.InsertOneResult does not implement the Access behaviour?

### ISSUE THREAD

**Issue by ardian-c** [ankhers/mongodb_ecto#145]
Hi, 

Thanks for the package. I'm a newbie with Elixir (Phoenix) so I'm having some trouble. Basically, I'm trying to create new user through API and get the token from Guardian package. Here is my code:

```
def create(conn, params) do  

    changeset_new_user = User.registration_changeset(%User{}, params)

    case Mongo.insert_one(:mongo, "users", changeset_new_user.changes, [return_document: :after, upsert: :true]) do
      {:ok, user} ->
        new_conn = Guardian.Plug.api_sign_in(conn, user, :access)
        jwt = Guardian.Plug.current_token(new_conn)

        new_conn
        |> put_status(:created)
        |> render(TrackerApiWeb.SessionView, "show.json", user: user, jwt: jwt)
      {:error, changeset} ->
        conn
        |> put_status(:unprocessable_entity)
        |> render(TrackerApiWeb.ChangesetView, "error.json", changeset: changeset)
    end
```

This creates new user, however it raises the following error. 
`function Mongo.InsertOneResult.fetch/2 is undefined (Mongo.InsertOneResult does not implement the Access behaviour)`. Further the `Guardian.Plug.api_sign_in(conn, user, access)` does not create the token I need. Can you provide me with some direction, I tried looking for solutions and went through documentation provided in mongo.ex with no results.

**Comment by ankhers** [comment]
You do not appear to be using this package (`mongodb_ecto`) in this example. You may want to file it against [ankhers/mongodb](https://github.com/ankhers/mongodb) in case other people are having a similar issue. 

However, I also noticed your post on the [elixir forum](https://elixirforum.com/t/trouble-with-inserting-into-mongodb/9921) and you are using `Repo.insert/4` instead of `Mongo.insert_one/4`. I can help out, but I will need to to which you are actually trying to use.

**Comment by ardian-c** [comment]
Yes I did try to do some updates, all the info from the elixir forum are the latest, so I'm using them.  The error when doing that is that I get `function Mongo.Ecto.insert/6 is undefined or private. Did you mean one of:
      * insert/5` which prompts me to use the other function but I'm confused why since I'm only passing the changeset. Should I remove any attributes from the changeset?

**Comment by ankhers** [comment]
That would be a miss-match with the `ecto` and `mongodb_ecto` packages. Based on what you have on the forum, you have

```
{:mongodb_ecto, github: "zeroasterisk/mongodb_ecto", branch: "elixir-ecto-v2.0.1"},
{:ecto, "~> 2.0"},
```

I am unfamiliar with that fork of this repository. If you want to use Ecto 2.0, you should use `{:mongodb_ecto, github: "ankhers/mongodb_ecto", branch: "ecto-2"}`. That should work correctly for you. I used it in production for quite a while until I recently changed to the `ecto-2.1` branch.

**Comment by ardian-c** [comment]
I did change the `mongodb_ecto` and added override the `ecto` package so deps are now updated.  However, I'm still getting the same error though.

**Comment by ankhers** [comment]
Are you absolutely positive that you downloaded and compiled the latest dependencies? Based on that error you have ecto 2.1 but you are trying to use a version of this package that required ecto 2. Take a look at what is in your `mix.lock` file.

**Comment by ardian-c** [comment]
I did run `mix deps.get` and `mix deps.compile` before running `mix.phoenix.server`. Here is my mix.exs file:
```def application do
    [
      mod: {TrackerApi.Application, []},
      applications: [
        :phoenix, :phoenix_pubsub, :gettext,
        :phoenix_ecto, :mongodb, :mongodb_ecto, :ecto,
        :cowboy, :logger,
        :poolboy, :uuid,
        :comeonin, :scrivener_ecto, :corsica
      ],
      extra_applications: [:runtime_tools]
    ]
  end

  # Specifies which paths to compile per environment.
  defp elixirc_paths(:test), do: ["lib", "test/support"]
  defp elixirc_paths(_),     do: ["lib"]

  # Specifies your project dependencies.
  #
  # Type `mix help deps` for examples and options.
  defp deps do
    [
      {:phoenix, "~> 1.2.1"},
      {:plug, "~>1.3.5", override: true},
      {:phoenix_pubsub, "~> 1.0"},
      {:phoenix_ecto, github: "phoenixframework/phoenix_ecto", ref: "v3.0.1"},
      {:mongodb, ">= 0.0.0"},
      {:mongodb_ecto, github: "ankhers/mongodb_ecto", branch: "ecto-2"},
      {:ecto, "~> 2.0", override: true},
      {:gettext, "~> 0.11"},
      {:uuid, "~> 1.1" },
      {:timex, "~> 3.0"},
      {:cowboy, "~> 1.0"},
      {:comeonin, "~> 2.5"},
      {:guardian, "~> 0.14.0"},
      {:corsica, "~> 0.5.0"},
      {:scrivener_ecto, "~> 1.0"}
    ]
  end```

# my mix.lock part:

```   "mongodb": {:hex, :mongodb, "0.2.1", "7050e90beb00f6a6455eec97140afbf9a57d0437d05eb538c8fef44491b755a3", [:mix], [{:connection, "~> 1.0", [hex: :connection, repo: "hexpm", optional: false]}, {:db_connection, "~> 1.0", [hex: :db_connection, repo: "hexpm", optional: false]}], "hexpm"},
  "mongodb_ecto": {:git, "https://github.com/ankhers/mongodb_ecto.git", "149bcc42dd07b7c304fc4afc8be4a4447399d6c1", [branch: "ecto-2"]},
  "phoenix": {:hex, :phoenix, "1.2.5", ```

**Comment by ankhers** [comment]
Can you find the line in the lock file that corresponds to the ecto version?

**Comment by ardian-c** [comment]
`  "ecto": {:hex, :ecto, "2.2.6", "3fd1067661d6d64851a0d4db9acd9e884c00d2d1aa41cc09da687226cf894661", [:mix], [{:db_connection, "~> 1.1", [hex: :db_connection, repo: "hexpm", optional: true]}, {:decimal, "~> 1.2", [hex: :decimal, repo: "hexpm", optional: false]}, {:mariaex, "~> 0.8.0", [hex: :mariaex, repo: "hexpm", optional: true]}, {:poison, "~> 2.2 or ~> 3.0", [hex: :poison, repo: "hexpm", optional: true]}, {:poolboy, "~> 1.5", [hex: :poolboy, repo: "hexpm", optional: false]}, {:postgrex, "~> 0.13.0", [hex: :postgrex, repo: "hexpm", optional: true]}, {:sbroker, "~> 1.0", [hex: :sbroker, repo: "hexpm", optional: true]}], "hexpm"},`

**Comment by ankhers** [comment]
You appear to be using ecto 2.2.6, which this adapter does not yet work with. Try using ecto `~> 2.0.0` version.

**Comment by ardian-c** [comment]
I did that, I can add users but it shows the following error now: 
``` function TrackerApiWeb.User.fetch/2 is undefined (TrackerApiWeb.User does not implement the Access behaviour)```

**Comment by ankhers** [comment]
That wouldn't be anything to do with this adapter. Though, if you show the full stack trace I may be able to help you figure out what the issue is.
