### ISSUE TITLE
Example how use with phoenix > 1.3

### ISSUE THREAD

**Issue by Fudoshiki** [ankhers/mongodb_ecto#153]
Hello, exists any example?

**Comment by ankhers** [comment]
There is nothing specific to do for Phoenix. It is just an ecto adapter. In your Repo configuration, just make sure you have `adapter: Mongo.Ecto`. Take a look at the [README.md](https://github.com/ankhers/mongodb_ecto/blob/master/README.md) in this repo for an exampe of how to do that.
