### ISSUE TITLE
Can't get by id

### ISSUE THREAD

**Issue by Lazarus404** [ankhers/mongodb_ecto#156]
Okay, this seems like it should be easy, but it isn't

```
%Mongo.InsertOneResult{inserted_id: %BSON.ObjectId{} = id} = Mongo.insert_one(MongoPool, @collection, data)
Mongo.find(MongoPool, @collection, %{"_id" => BSON.ObjectId.encode!(id)}, [])
|> IO.inspect()
```
outputs `nil`.  If I pass in the `ObjectId` instance directly, it's also nil.  What is the magic sauce to pull by ID?  I can pull by any other value of the document, but not the `_id` value.

Thanks

**Comment by Lazarus404** [comment]
In case it helps, if I do a `find`, the cursor looks like this:
```
%Mongo.Cursor{
  coll: "users",
  conn: #PID<0.1828.0>,
  opts: [slave_ok: true, pool: DBConnection.Poolboy],
  query: %{
    "_id" => %{"value" => <<91, 70, 2, 4, 158, 207, 41, 92, 78, 59, 75, 126>>}
  },
  select: nil
}
```

**Comment by ankhers** [comment]
You do not want to encode the `id` that you get back. You already have it in the proper representation to query.

```
%Mongo.InsertOneResult{inserted_id: %BSON.ObjectId{} = id} = Mongo.insert_one(MongoPool, @collection, data)
Mongo.find(MongoPool, @collection, %{"_id" => id}, []) |> Enum.to_list()
```

That will return the record.

**Comment by Lazarus404** [comment]
Nope, it doesn't.  If I pass the id object as is, I still get nil.  I can pull by any other value of the document, but not the _id.

I am using a replication set.

**Comment by ankhers** [comment]
```
iex(1)> {:ok, pid} = Mongo.start_link(database: "test")
{:ok, #PID<0.172.0>}
iex(2)> {:ok, %{inserted_id: id}} = Mongo.insert_one(pid, "foo", %{foo: 12})
{:ok,
 %Mongo.InsertOneResult{inserted_id: #BSON.ObjectId<5b4618eeb3acd982a6b9340f>}}
iex(3)> Mongo.find(pid, "foo", %{_id: id}) |> Enum.to_list
[%{"_id" => #BSON.ObjectId<5b4618eeb3acd982a6b9340f>, "foo" => 12}]
```

(I'm closing this an reopening a ticket in the ankhers/mongodb repo because this does not have anything to do with the ecto adapter)
