### ISSUE TITLE
Help required while trying to use Mongo.Ecto.ChangeMap

### ISSUE THREAD

**Issue by TestFirebaseLogin** [ankhers/mongodb_ecto#157]
i have a field of type map in ecto schema.I want to update a field in it.
But iam unable to proceed further.
I followed the link

https://hexdocs.pm/mongodb_ecto/Mongo.Ecto.ChangeMap.html#content

I keep on receiving this error....
** (exit) an exception was raised:
    ** (Ecto.Query.CastError) deps/ecto/lib/ecto/repo/queryable.ex:88: value `%Mongo.Ecto.ChangeMap{field: "namek", value: "namev1"}` in `update` cannot be cast to type :map in query:

Any help shall be highly appreciated.

**Comment by ankhers** [comment]
Unfortunately there are not tests around `ChangeMap` and `ChangeArray`. I have also never touched that code, nor used that functionality myself.

I think we should start by adding tests and then we can look into fixing it.

**Comment by TestFirebaseLogin** [comment]
Hi ankers,thanks for the reply.
I am using this...
     {:mongodb_ecto, github: "michalmuskala/mongodb_ecto", branch: "ecto-2.1"},
      {:ecto, "~> 2.1.0"}

Also i could get rid of above error,by adding type of field which i wanted to update in schema as Mongo.Ecto.ChangeMap.
For the time i have moved out of mongo ecto and using mongodb driver for elixir.
If you have better links for updating nested document,please share,as i had to change a lot of code while moving away from using Ecto.
Thanks

**Comment by ankhers** [comment]
You could continue using Ecto alongside the mongodb driver.

```
Mongo.find(MyApp.Repo.Pool, collection, filter, opts)
```

We have also been talking about adding something like `Mongo.Ecto.Raw.find(MyApp.Repo, collection, filter, opts)` in order to make it a bit easier to use the ecto adapter and raw mongo calls where necessary.

**Comment by TestFirebaseLogin** [comment]
Ok thanks for reply ankers.
Just a doubt,if i want to use ecto repo with mongodb driver,should i still write this line in mine application.ex?
 worker(Mongo, [[name: :mongo, database: "test", pool: DBConnection.Poolboy, url: "mongodb://***User:***Pass@server-ip:27017/***Database"]])

Thanks

**Comment by ankhers** [comment]
No. this adapter uses the `mongodb` package, so it already starts the worker.

**Comment by TestFirebaseLogin** [comment]
Ok thanks,ankers,i will close the issue for now,and use mongodb driver.Incase of any other doubts,i would message u on slack.
Thanks
