### ISSUE TITLE
like()

### ISSUE THREAD

**Issue by Orange-Men** [ankhers/mongodb_ecto#164]
Hi!
branch: "ecto-2.1"
I trying to use [like/2.](https://hexdocs.pm/ecto/Ecto.Query.API.html#like/2)
But something is broken and I get the error:
```
** (Ecto.QueryError) Invalid expression for MongoDB adapter in where clause in query:
from a in MyApp.Airport,
       where: like(a.city, "Br%"),
       select: a
```
source code:
```
    query = from a in Airport, where: like(a.city, "Br%")
    Repo.all(query)
```

**Comment by ankhers** [comment]
`like/2` does not translate to non-SQL databases well. The syntax used is very specific to SQL. Have you taken a look at the [regex module](https://hexdocs.pm/mongodb_ecto/Mongo.Ecto.Regex.html) that this package provides? Maybe that can help you in this scenario.

**Comment by Orange-Men** [comment]
@ankhers Thank you very much!
