### ISSUE TITLE
Red tests

### ISSUE THREAD

**Issue by exAspArk** [ankhers/mongodb_ecto#168]
I noticed that there are 17 tests which are failing both locally and in [TravisCI](https://travis-ci.org/ankhers/mongodb_ecto/builds/456479986). Would you consider removing or muting those tests since they don't provide any value? I could help to ✂️  or mute them :)

P.S. ~TravisCI didn't trigger for this PR https://github.com/ankhers/mongodb_ecto/pull/167 for some reason.~ Force-push triggered the build

**Comment by ankhers** [comment]
I am currently not interested in removing or muting them. The current 2.x branch will no longer be worked on. I believe I will be started from scratch when starting Ecto 3.x support.
