### ISSUE TITLE
Javascript in "where" clause not behaving as expected in Phoenix

### ISSUE THREAD

**Issue by lostboy** [ankhers/mongodb_ecto#60]
Hopefully this is just my own lack of understanding but i'm trying to use mongodb_ecto (0.1.2 or HEAD) in a Phoenix (1.1.2) app with Phoenix Ecto (2.0.0). 

I'm trying to use javascript in the where clause as documented but it complains of 

```
** (Ecto.QueryError) web/models/post.ex:15: value `%Mongo.Ecto.JavaScript{code: "this.value == count", scope: [count: 1]}` in `where` cannot be cast to type :boolean in query:
```

The model looks something like this

```
defmodule Project.Post do
  use Project.Web, :model

  import Ecto.Query, only: [from: 2]
  import Mongo.Ecto.Helpers

  alias Project.Repo

  schema "posts" do
    field :value, :integer
  end

  def test
    j = Mongo.Ecto.Helpers.javascript "this.value == count", count: 1
    q = from p in Project.Post, where: ^j
    Repo.all q
  end
end
```

The stacktrace seems to suggest that mongodb_ecto isn't even getting a look in so this quite possibly is a phoenix_ecto bug?

```
    (elixir) lib/enum.ex:1387: Enum."-reduce/3-lists^foldl/2-0-"/3
    (elixir) lib/enum.ex:1102: Enum."-map_reduce/3-lists^mapfoldl/2-0-"/3
      (ecto) lib/ecto/repo/queryable.ex:91: Ecto.Repo.Queryable.execute/5
      (ecto) lib/ecto/repo/queryable.ex:15: Ecto.Repo.Queryable.all/4
    (stdlib) erl_eval.erl:669: :erl_eval.do_apply/6
       (iex) lib/iex/evaluator.ex:117: IEx.Evaluator.handle_eval/5
       (iex) lib/iex/evaluator.ex:110: IEx.Evaluator.do_eval/3
       (iex) lib/iex/evaluator.ex:90: IEx.Evaluator.eval/3
```

Could you shed any light?

**Comment by michalmuskala** [comment]
What's the ecto version?

**Comment by lostboy** [comment]
Ecto is 1.1.1

**Comment by michalmuskala** [comment]
Ecto 1.1 unfortunately broke this feature. I'll be working today on fixing it.

**Comment by lostboy** [comment]
Thanks @michalmuskala, I thought I was doing something wrong.

**Comment by michalmuskala** [comment]
Hey, I'm not sure if you were following other issues here, if not here's a quick rundown:

Unfortunately Ecto 1.1 broke some things for us and for the time being `mongo_ecto` is not compatible with Ecto 1.1. Even more unfortunately, right now, I have no time I could spare to fix those issues. Because of this, unless something changes, `mongo_ecto` will target the future release of Ecto 2.0 that should happen in about a month.

**Comment by ankhers** [comment]
I am going to close this. The JavaScript feature has been broken for a while and is being tracked in #106.
