### ISSUE TITLE
fragment_condition OR condition produces invalid Mongo query

### ISSUE THREAD

**Issue by arkadiyk** [ankhers/mongodb_ecto#77]
`where([p], fragment("participants.delegate_id": 123445) or p.is_presentation == true)`
produces:
`%{"$or": [[["participants.delegate_id": 123445]], [is_presentation: true]]}`

I think it puts unnecessary nesting for the fragment condition into the normalized query.

Not fragment conditions look like this:
`where([p], p.is_presentation == true or p.is_presentation == true)`
makes
`%{"$or": [[is_presentation: true], [is_presentation: true]]}}`
which executes just fine..

**Comment by ankhers** [comment]
I believe this has been fixed on either the `ecto-2` or `ecto-2.1` branch.
